from db import get_products_collection

raw_data = """Product Name	Industry	Category	Price	Colors	Quality Type	Subquality	Fitting	Sizes	Description	Product Codes	Image Set - Order:	Image Set - Varying:
Blankets	Healthcare, Hospitality	Bedding	Contact for Prices	Grey, Navy Blue, Cream, Maroon, Brown	1000g, 750g	NA	NA	60x90	Premium hospital blankets, plain, single bed size (60x90). Heavy woolen warm blanket designed for patient comfort. Breathable fabric, fade resistant, skin friendly, reusable blankets. Easy to wash and quick-dry material.	4144	Blanket101, Blanket102(a-e), Blanket103	Blanket102a = Grey, Blanket102b = Navy Blue, Blanket102c = Cream, Blanket102d = Maroon, Blanket102e = Brown
Hospital Bedsheet Set	Healthcare	Bedding	Contact for Prices	White, Light Grey, Grey, Dark Grey, Navy Blue, Coffee Brown, Tan, Maroon	Pressed Stripes , Minimal Stripes, Lifted Stripes	Pressed Stripes: [60/40 PC, 80/20 PC], Minimal Stripes: [60/40 PC, 70/30 PC], Lifted Stripes: [70/30 PC, 80/20 PC]	NA	60x90 (Bedsheet), 17 x 26 (Pillow Cover)	Premium linen hospital bedsheet, single bed size (60x90). Cool, cotton-feel fabric, breathable and comfortable, designed for a restful sleep experience. Easily washable.	60099	Bedsheet101, Bedsheet103(a-h), Bedsheet104	Bedsheet103a = White, Bedsheet103b = Light Grey, Bedsheet103c = Grey, Bedsheet103d = Dark Grey, Bedsheet103e = Navy Blue, Bedsheet103f = Coffee Brown, Bedhseet103g = Tan, Bedsheet103h = Maroon
Bedsheets	Hospitality	Bedding	Contact for Prices	White, Light Grey, Grey, Dark Grey, Navy Blue, Coffee Brown, Tan, Maroon	Pressed Stripes , Minimal Stripes, Lifted Stripes	Pressed Stripes: [60/40 PC, 80/20 PC], Minimal Stripes: [60/40 PC, 70/30 PC], Lifted Stripes: [70/30 PC, 80/20 PC]	NA	60x90, 100x100, 108x100, 90x100, 108x108, 72x112, 96x100, 90x108, 108x112, 96x108	Premium linen bedsheet, single bed size (60x90). Cool, cotton-feel fabric, breathable and comfortable, designed for a restful sleep experience. Easily washable.	60099	Bedsheet101, Bedsheet102(a-h), Bedsheet104	Bedsheet102a = White, Bedsheet102b = Light Grey, Bedsheet102c = Grey, Bedsheet102d = Dark Grey, Bedsheet102e = Navy Blue, Bedsheet102f = Coffee Brown, Bedhseet102g = Tan, Bedsheet102h = Maroon
Door Mats	Healthcare, Hospitality	Furnishing	Contact for Prices	As per req	Rubber Mat	NA	NA	20in x 30in, 24in x 35in, 32in x 40in	Premium door mats, strong and durable, anti-skid backing, absorb moisture and dirt, supersoft, easy to clean and versatile use.	41134	DoorMat01, DoorMat02	
Bed Mats	Healthcare, Hospitality	Furnishing	Contact for Prices	As per req	As per req	NA	NA	20in x 55in, 22in x 55in, 16in x 48in, 20in x 70in	Made from premium quality material, soft, comfortable and skin-friendly. Durable and suitable for daily use, easy to clean and maintain. Available in various designs, lightweight and eco-friendly material.	41224	BedMat01, BedMat02, BedMat03, BedMat04	
Pillows	Hospitality	Bedding	Contact for Prices	White	Fiber	NA	NA	17x27, 20x30, 20x26, 20x28, 20x36	Designed to be supersoft and breathable, skin-friendly, easy to maintain, durable and available in all sizes.	41404	Pillow01	
Cushions	Hospitality	Bedding	Contact for Prices	White	PC Quilting	NA	NA	16x16, 18x18, 24x24	Designed to be supersoft and breathable, skin-friendly, easy to maintain, durable and available in all sizes.	42214	Cushion01	
Bed Runners	Hospitality	Bedding	Contact for Prices	As per req	PC Quilting Filling Runners	NA	NA	18x60, 18x90	Luxury hotel-style bed runner set with two matching cushion covers, premium quilted fabric for a soft touch and rich look. Perfect for hotels and guest rooms.	42304	BedRunner01, BedRunner02, BedRunner03, BedRunner04, BedRunner05, BedRunner06, BedRunner07	
Comforters	Hospitality	Bedding	Contact for Prices	White	Fiber Filling Comforters	NA	NA	60x90, 100x100, 108x100, 90x100, 108x108, 72x112, 96x100, 90x108, 108x112, 96x108	Our comforters and duvets are crafted for warmth, softness, and long-lasting comfort. Made with high-quality filling and breathable fabric, they provide cozy insulation while remaining lightweight. Easy to maintain and durable, they are perfect for homes and hotels, offering both luxury and practicality for restful sleep.	43024	Comforter01	
Scrubs	Healthcare	Uniforms	Contact for Prices	Blue, Black, Grey, Pastel Green, Maroon, Sky Blue, Navy Blue	PCL, SPL, PCM	NA	Male, Female, Unisex	28-44	These scrubs are comfortable, flexible and stretch freely while staying supersoft and breathable throughout long shifts. Made from anti-wrinkle fabric, they remain smooth and professional all day. The featherlight feel ensures comfort, while excellent shape retention keeps them looking fresh and perfectly fitted, wash after wash.	500045	Scrub01(a-g)	Scrub01a = Sky Blue, Scrub01b = Blue, Scrub01c = Navy Blue, Scrub01d = Pastel Green, Scrub01e = Maroon, Scrub01f = Grey, Scrub01g = Black
OT Gowns	Healthcare	Gowns	Contact for Prices	Green, Blue, Grey, Khaki	PCM, 100% Cotton	NA	NA	Medium (Free Size), Large (Free Size)	OT gowns give full coverage with a wrap-around design and a comfortable fit. They are easy to wear and remove, made from breathable, lint-free fabric, and have soft cuffs for extra comfort. Strong, hygienic, and reliable, they ensure safety during medical use.	500135	OTgown01(a-d)	OTgown01a = Blue, OTgown01b = Green, OTgown01c = Khaki, OTgown01d = Grey
Adult Patient Gowns	Healthcare	Gowns	Contact for Prices	Pink, Maroon, Blue, Green	SC, PC	NA	NA	Medium (Free Size), Large (Free Size)	Our adult patient gowns are soft, breathable, and comfortable. With a back tie-up closure and full coverage, they are easy to use, lightweight, and reusable. Perfect for hospitals, clinics, and long-term care.	500225	AdultPatientGown01, AdultPatientGown02, AdultPatientGown03, AdultPatientGown04, AdultPatientGown05, AdultPatientGown06	
Pediatric Patient Gowns	Healthcare	Gowns	Contact for Prices	Cartoon Designs	SC, Premium Smooth Pc	NA	NA	1-2 Yrs, 3-5 Yrs, 6-8 Yrs, 9-11 Yrs, 12-14 Yrs	Our pediatric patient gowns are soft, breathable, and comfortable. With a back tie-up closure and full coverage, they are easy to use, lightweight, and reusable. Perfect for hospitals, clinics, and long-term care.	500315	PediatricPatientGown01, PediatricPatientGown02, PediatricPatientGown03, PediatricPatientGown04, PediatricPatientGown05	
Sarees for staff	Healthcare, Hospitality, Schools	Uniforms	Contact for Prices	Khaki, Navy Blue, Pink, Grey, Sky Blue, Maroon	As per req	NA	NA	Standard Size, (As Per Req/Hospital Theme)	Blended fabric, low maintenance, iron free material, durable and long-lasting. Safe for handwash/machinewash.	500405	StaffSaree01(a-f)	StaffSaree01a = Sky Blue, StaffSaree01b = Navy Blue, StaffSaree01c = Pink, StaffSaree01d = Maroon, StaffSaree01e = Khaki, StaffSaree01f = Grey
Nursing Unifroms	Healthcare	Uniforms	Contact for Prices	White, Sky Blue, Pink, Lavender, Pista Green, Navy Blue, Forest Green, Maroon, Wine	PCL, SPL, PCM	NA	Male, Female, Unisex	28-44	Skin-friendly, lightweight, fade-resistant, ultrasoft, antiwrinkle, stain-resistant, and perfect for long shifts.	501035	NurseUniform01(a-i)	NurseUniform01a = Sky Blue, NurseUniform01b = White, NurseUniform01c = Navy Blue, NurseUniform01d = Pink, NurseUniform01e = Lavender, NurseUniform01f = Wine, NurseUniform01g = Pista Green, NurseUniform01h = Maroon, NurseUniform01i = Forest Green
OT Nursing Staff Uniforms	Healthcare	Uniforms	Contact for Prices	White, Sky Blue, Pink, Lavender, Pista Green, Navy Blue, Forest Green, Maroon, Wine	PC, SP, Mattyfinishing	NA	Male, Female, Unisex	28-44	Skin-friendly, lightweight, fade-resistant, ultrasoft and perfect for long shifts, antiwrinkle, stain-resistant.	501125	NurseUniform01(a-i)	NurseUniform01a = Sky Blue, NurseUniform01b = White, NurseUniform01c = Navy Blue, NurseUniform01d = Pink, NurseUniform01e = Lavender, NurseUniform01f = Wine, NurseUniform01g = Pista Green, NurseUniform01h = Maroon, NurseUniform01i = Forest Green
Front Office staff Uniforms	Healthcare, Hospitality	Uniforms	Contact for Prices	As per req	As per req	NA	Male, Female, Unisex	Male: 31-44, Female: 32-44, Unisex: 33-44	Designed for style and comfort, easy to wash.	501215	FrontStaffUniform01, FrontStaffUniform02, FrontStaffUniform03	
OT Aaya Nightys	Healthcare	Uniforms	Contact for Prices	Green, Blue, Pink, Grey	PCM	NA	NA	Medium, Large	Soft and breathable fabric, freesize for universal fit, easy to wear and remove, durable and reusable material, allows easy movement and flexibility.	501305	OTAayaNighty01(a-d)	OTAayaNighty01a = Blue, OTAayaNighty01b = Pink, OTAayaNighty01c = Green OTAayaNighty01d = Grey
House Keeping Jackets	Healthcare, Hospitality	Uniforms	Contact for Prices	As per req	PCL, PCM	NA	Male, Female, Unisex	28-44	Durable and comfortable. Modren & sleek design, comfortable for long hours, multi-industry use.	40054	HouseKeeping01, HouseKeeping02, HouseKeeping03, HouseKeeping04, HouseKeeping05	
Watchmen Uniforms	Healthcare, Schools	Uniforms	Contact for Prices	Grey, Blue, Green	Premium Quality, Medium Quality	NA	Male	28-44	Professional design with embroidered patches on chest and sleeves, complete uniform look with functional pockets. Full-length sleeves provide complete arm coverage and a professional look.	40144	Watchmen01(a-c)	Watchmen01a = Blue, Watchmen01b = Grey, Watchmen01c = Green
Front Office Punjabi Dress	Healthcare	Uniforms	Contact for Prices	As per req	PC, SP	NA	Female	Dress Material	Premium material, convennient and comfortable, skin friendly, breathable and perfect for long shifts, suitable for hospital staff.	40234	FrontPunjabi01, FrontPunjabi02	
Doctor Aprons	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Only White	SP, PC	NA	Half Sleeve, Full Sleeve	28-44	Designed for professional who seek comfort, durability and a clean professional appearance. Made from high-quality fabric. Breathable, comfort-fit, and easy to maintain.	40324	DoctorApron01, DoctorApron02	
Surgical caps	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Denim, Grey, Green, Black, Blue, Pink	Denim Cotton, PCM, Department Wise Caps (SC, SP)	NA	Unisex	Free Size	Complete hair barrier, comfort for prolonged wear. Durable material allows for repeated use.	40414	SurgicalCap01(a-f)	SurgicalCap01a = Blue, SurgicalCap01b = Pink, SurgicalCap01c = Grey, SurgicalCap01d = Black, SurgicalCap01e = Green, SurgicalCap01f = Denim
Hand towels for doctors	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Navy Blue, Sky Blue, Lite Green, Pink, White, Cream	Cotton	NA	Unisex	12in x 12in, 16in x 24in, 18in x 30in	Ultra-soft texture, highly absorbent, durable and long-lasting. Fade-resistant colors, lightweight and eco-friendly.	40504	DoctorHandTowel01	
Surgical Tray Fabric	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Navy Blue, Green	100% Handloom Cotton	NA	Unisex	15in x 18in, 20in x 20in, 18in x 30in, 30in x 30in, 35in x 35in, 39in x 39in, 39in x 59in, 50in x 50in, 47in x 39in, 75in x 75in, 1M x 1.5M, 1.5M x 1.5M, 2M x 1.5M	100% cotton. Comfort during surgery. Absorbent, breathable, reusable and machine washable.	41044	SurgicalTrayFabric01	
Pillow Covers	Hospitality	Bedding	Contact for Prices	White, Grey, Navy Blue	PC	NA	NA	17x26, 20x30, 23x33	Premium fabric, lightweight, breathable and comfortable, skin friendly, feather feel.	42034	PillowCover01	
Folding Bed	Healthcare	Medical Equiptment & Supplies	Contact for Prices	NA	Fine foam material	NA	NA	3ft x 6ft	Lightweight and portable, made with high-quality foam material. Comfortable, supportive foam construction to ensure back support and relaxation.	42124	FoldingBed01	
Bath Towel	Hospitality	Bath	Contact for Prices	Custom - Customer Request	Terry Cotton	NA	NA	27x54, 30x60, 36x72 (Custom sizes available)	Highly absorbent, quick-dry, durable, ultrasoft, premium quality and long-lasting, available in all sizes.	43114	BathTowel01	
Hand Towel	Hospitality	Bath	Contact for Prices	Custom - Customer Request	Terry Cotton	NA	NA	16x16, 16x24 (Custom sizes available)	Highly absorbent, quick-dry, durable, ultrasoft, lightweight, premium quality and long-lasting, available various sizes.	43204	HandTowel01	
Curtains	Healthcare, Hospitality	Furnishing	Contact for Prices	Pink, Green, Blue	Depends on Customer requirement	NA	NA	All Sizes Available	Easy maintenance, resistant to shrinkage, wrinkle-free and fade-resistant.	44014	Curtain01, Curtain02, Curtain03, Curtain04, Curtain05, Curtain06	
Crepe Bandage	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Orange, Red	Cotton Elastic Material	NA	NA	6cm x 4M, 8cm x 4M, 10cm x 4M, 15cm x 4M	Premium quality crepe bandage. Designed to provide effective support, stability and comfort. Made from premium quality cotton yarn with excellent elasticity. Durable and smooth.	44104	CrepeBandage01(a-b)	CrepeBandage01a = Orange, CrepeBandage01b = Red
Stethoscope	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Available in all colors	Standard, High Quality	NA	NA	Standard Size	High acoustic sensitivity. Designed for clear auscultation of heart, lung and body sounds, premium stainless steel chest piece. Excellent sound condition, durability and long-lasting professional performance.	45004	Stethoscope01	
Gauze	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Made up of premium cotton yarns	NA	NA	4-Ply, 8-Ply, 10-Ply, 12-Ply	Made of soft and breathable cotton. Ideal for dressings and providing minimal support to wound areas. Stretchable and stays in place. Lightweight and comfort, available in different sizes.	700297	Gauze01	
Cotton Roll	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Fine Cotton	NA	NA	Absorbent Cotton Roll, Surgical Cotton Roll	This cotton roll is soft and fluffy. It is a fast-absorbent cotton wool. Eco-friendly and chemical free. Made from 100% pure and hygienic cotton for safe use. Soft and skin-friendly.	700477	CottonRoll01	
Hand Gloves / Surgical Gloves	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White, Blue, Violet	Latex gloves, Nitrile gloves	NA	NA	S, M, L	Excellent barrier protection with high level of tactile sensitivity, perfectly fitting and high strength and puncture resistant. Medical grade protection, versatile application.	700567	SurgicalGlove01	
Disposable Bedsheets	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White, Blue, Black	Non-Woven Material	NA	NA	30x72, 32x82, 82x36 (30-45 GSM); 47x82, 60x90 (45-60 GSM, OT)	Skin-friendly, hyginic, comfortable to wear, economical and disposable, durable and eco-friendly. Lightweight and breathable. Ideal for use in hospitals.	700657	DisposableBedsheet01	
Disposable Hair caps	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Blue	Non-Woven Material	NA	NA	18in, 21in, 24in (Free Size)	Lightweight, feels comfortable and easy to use. Made from breathable non-woven fabric. Full head coverage. Single use for reliable hygiene.	700747	DisposableHairCap01	
Newborn Baby Kit	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Various Designs	Made up of Fine Cotton	NA	NA	16, 20, 24 Products Pack	Made using breathable cotton fabric, easy care, comfort during sleeping, resting and daily use for early infant months.	700837	BabyKit01	
Kitchen Aprons	Hospitality	Uniforms	Contact for Prices	Various Designs	50-50 PC Fabric	NA	NA	Standard, Small, Large/Extra Large	Premium full-length apron. Made from high-quality polyster-cotton. Breathable, lightweight and designed for all-day wear with adjustable neck and waist ties for a custom fit.	700927	KitchenApron01, KitchenApron02	
BP Machines	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Digital Sensor	NA	NA	Wrist Machine, Hand Cuff Machine	Clinically validated for high accuracy. Universal size cuff, fits arm sizes 22cm-42cm. Irregular heartbeat indicator. Accurate blood pressure monitoring. User-friendly digital display. Simple operation interface.	701197	BPMachine01	
Nebulizer	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Standard	NA	NA	Standard Size	Fast and effective nebulization. Easy to clean and easy to use, powerful performance. Handy in usage, comes with flow adjuster.	701287	Nebulizer01	
Surgical Trays	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Silver	Medical Grade Stainless Steel	NA	NA	8x3, 8x6, 9x5, 10x8, 11x7, 12x10, 12x8, 14x10, 12x15, 18x12	Premium surgical-grade stainless steel. Durable, rust-proof. Multi-purpose medical utility, available in all sizes. Seamless design prevents bacterial growth.	701377	SurgicalTray01	
PPE KITS	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White, Blue	Disposable Material	NA	NA	Standard Size	Crafted with high-quality materials. This premium quality PPE kit ensures durability and comfort throughout the day or extended use. Complete protection set.	701467	PPEKit01	
Hospital Beds	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Standard	Heavy Metal	NA	NA	Fully Automated, Semi Automated, Manual Bed, ICU Bed	This bed comes with head adjustable, side railing for safety and comes with IV stand. Perfect for homes, healthcare and hospital. Durable construction, easy to use.	701557	HospitalBed01	
Disposable Masks (3-Ply, N95)	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Blue, Black	Non-Woven Material	NA	NA	3-Ply Masks, N95 Masks	This disposable face mask comes with soft elastic earloops and are comfortable to wear for long hours. It has a flexible nose clip for better grip and protection.	701647	DisposableMask01	
Carpets	Hospitality	Furnishing	Contact for Prices	Various Designs	Velvet	NA	NA	All Sizes Available	Made from velvet with a rectangular shape, machine washable, durable, gives luxurious look to room. Anti-skid design helps the carpet stay more stable on the floor. Available in all sizes.	701737	Carpet01, Carpet02, Carpet03, Carpet04, Carpet05, Carpet06, Carpet07	
Comforter Cover	Hospitality	Bedding	Contact for Prices	White	PC	NA	NA	63x93, 103x103, 111x103, 93x103, 111x111, 75x115, 99x103, 93x111, 111x115, 99x111	Soft and skin friendly, easy care and premium quality. Comfortable and buttery soft feel. Perfect for everyday comfort and style.	701827	ComforterCover01	
Hospital Bags	Healthcare	Accessories	Contact for Prices	White, Half-White, Pink	PC	NA	NA	15x20, 15x24	High-quality custom bags.	41314	HospitalBag01	
Oxygen Cylinder	Healthcare	Medical Equiptment & Supplies	Contact for Prices	Black, Green	Seamless Steel	NA	NA	A-Type, B-Type, D-Type, Jumbo D	High-purity certified medical oxygen cylinder for safe, reliable home and clinical respiratory care. Built from durable, seamless steel with standard valves for precise and easy flow adjustments. Available in multiple sizes to perfectly suit portable, emergency, or long-term therapeutic needs.	700387	OxygenCylinder01	
Gauze pads	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Made up of premium cotton yarns	NA	NA	8x10, 10x12, 8x12, 10x18	Made from soft, strong, and durable woven cotton for comfort and effectiveness. Hygienic and quick-absorbent to efficiently manage fluids during medical procedures.	782737	GauzePads01	
Gauze Than	Healthcare	Medical Equiptment & Supplies	Contact for Prices	White	Made up of premium cotton yarns	NA	NA	90cm x 18M, 100cm x 16M, 80cm x 60M, 100cm x 18M, 100cm x 20M	Soft, breathable and gentle on skin for wound care. High absorbency suitable for cleaning and dressing. Ideal for hospitals, clinics, first-aid kits and home care.	783187	GauzeThan01	
"""

def seed_database():
    col = get_products_collection()
    col.delete_many({})

    lines = raw_data.strip().split("\n")
    headers = [h.strip() for h in lines[0].split("\t")]

    docs = []
    for line in lines[1:]:
        if not line.strip():
            continue
        parts = [p.strip() for p in line.split("\t")]
        while len(parts) < len(headers):
            parts.append("")

        row = dict(zip(headers, parts))

        industries = [i.strip() for i in row.get("Industry", "").split(",") if i.strip()]
        colors = [c.strip().replace("(", "").replace(")", "") for c in row.get("Colors", "").split(",") if c.strip()]
        sizes = [s.strip() for s in row.get("Sizes", "").split(",") if s.strip()]

        doc = {
            "product_name": row.get("Product Name"),
            "industries": industries,
            "category": row.get("Category"),
            "price": row.get("Price", "Contact for Prices"),
            "colors": colors,
            "quality_type": row.get("Quality Type"),
            "subquality": row.get("Subquality"),
            "fitting": row.get("Fitting"),
            "sizes": sizes,
            "description": row.get("Description"),
            "product_code": row.get("Product Codes"),
            "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80"
        }
        docs.append(doc)

    result = col.insert_many(docs)
    print(f"Successfully inserted {len(result.inserted_ids)} products into MongoDB Atlas!")

if __name__ == "__main__":
    seed_database()